### ISSUE TITLE
PHPStorm Exception - Not a JSON Array: null

### ISSUE THREAD

**Issue by calebergh** [Jardinero/stylelint-plugin#15]
This exception appears to prevent the StyleLint plugin from running properly at all:

PhpStorm 2018.3
Build #PS-183.4284.150, built on November 21, 2018
JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

```
annotator: com.jokerzoid.intellij.plugin.stylelint.StylelintAnnotator@6c6a2388 (class com.jokerzoid.intellij.plugin.stylelint.StylelintAnnotator)

java.lang.IllegalStateException: Not a JSON Array: null
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:107)
	at com.jokerzoid.intellij.plugin.stylelint.ProcessManager.getOutput(ProcessManager.java:79)
	at com.jokerzoid.intellij.plugin.stylelint.ProcessManager.runStylelint(ProcessManager.java:42)
	at com.jokerzoid.intellij.plugin.stylelint.StylelintAnnotator.doAnnotate(StylelintAnnotator.java:41)
	at com.jokerzoid.intellij.plugin.stylelint.StylelintAnnotator.doAnnotate(StylelintAnnotator.java:19)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:184)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:40)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:158)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$10(BackgroundTaskUtil.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:264)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:243)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:157)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:336)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:326)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:276)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:290)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:245)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:356)
	at com.intellij.util.Alarm$Request.run(Alarm.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by aboutandre** [comment]
FYI: I just found out that **you don't need the plugin anymore**. With the plugin I was also running into errors.

I am running IntelliJ 2019.1 and everything works out of the box. I believe PHP Storm should also work.

Anyone could confirm this?

**Comment by anthonyvialleton** [comment]
@aboutandre Yes you are right, I'm using Intellij Idead 2019.1.x and I could remove the Stylelint plugin and it works. 

But my issue has been fixed by setting the file type of my SASS watcher to **any** instead of SASS for pointing to my .scss files. You can then define a scope for the watcher pointing to the .scss files.

Hope it helps
